#!/bin/sh

mode=$(makoctl mode)

if [ "$mode" = "default" ]; then
  class="off"
 elif [ "$mode" = "dnd" ]; then
  class="on"
 fi

if [ "$1" = "toggle" ]; then
  if [ "$mode" = "default" ]; then
    makoctl mode -s dnd
    class="on"
  elif [ "$mode" = "dnd" ]; then
    makoctl mode -s default
    class="off"
  fi
fi

printf '{"alt":"%s"}\n' "$class"
#echo "{\"alt\": \"${status}\"}"
