#!/bin/env sh

OPTIONS=$(echo -e "Logout\nReboot\nPoweroff" | fuzzel -d -p " " -w 15 -l 3)

case $OPTIONS in
  "Logout")
    loginctl terminate-user $USER
    ;;
  "Reboot")
    systemctl reboot
    ;;
  "Poweroff")
    systemctl poweroff
    ;;
  *)
    ;;
esac
